version: '3.9'

services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client1
    ports:
      - "8001:8001"
    volumes:
      - ./storage/client1:/app/storage
    networks:
      p2pnet:
        ipv4_address: 172.17.0.2

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client2
    ports:
      - "8002:8002"
    volumes:
      - ./storage/client2:/app/storage
    networks:
      p2pnet:
        ipv4_address: 172.17.0.3

  client3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client3
    ports:
      - "8003:8003"
    volumes:
      - ./storage/client3:/app/storage
    networks:
      p2pnet:
        ipv4_address: 172.17.0.4

networks:
  p2pnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
