version: '3'

services:
  client1:
    build: .
    container_name: client1
    networks:
      blockchain_net:
        ipv4_address: 172.27.0.2
    volumes:
      - ./client1:/app
    stdin_open: true
    tty: true

  client2:
    build: .
    container_name: client2
    networks:
      blockchain_net:
        ipv4_address: 172.27.0.3
    volumes:
      - ./client2:/app
    stdin_open: true
    tty: true

  client3:
    build: .
    container_name: client3
    networks:
      blockchain_net:
        ipv4_address: 172.27.0.4
    volumes:
      - ./client3:/app
    stdin_open: true
    tty: true

networks:
  blockchain_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
